### ISSUE TITLE
Refactor wiki-like, internal links to footlinks too. 

### ISSUE THREAD

**Issue by psyguy** [DahaWong/obsidian-footlinks#3]
Given that Obsidian [from v0.9.16 unward](https://forum.obsidian.md/t/obsidian-release-v0-9-16/8795) supports aliases for note names, I hope this feature (maybe in this [card](https://github.com/DahaWong/obsidian-footlinks/projects/1#card-51122886)?) is implemented sooner.

---

To give a hint of why I am eagerly looking forward to this feature, assume one of my notes is named `@wooldridge_2018_IntroductoryEconometricsModern` with the following YAML:

``` YAML
---

aliases:
  - 'Introductory econometrics: A modern approach'
  - 'Wooldridge (2018)'
  - '(Wooldridge, 2018)'

---
```

When I want to make an internal link to (a section of) this note via its alias, it becomes tediously long in edit mode:

```
[[@wooldridge_2018_IntroductoryEconometricsModern#Quotes and notes|Wooldridge (2018)]]
```

Which is quite lengthy for something that will render as `Wooldridge (2018)` in note preview.
